# Generated by Django 4.2.7 on 2023-11-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
